version: '3'

services:
  db:
    image: mysql/mysql-server:5.7.22
    ports:
      - 3306:3306
    volumes:
      - ./shared/schema:/docker-entrypoint-initdb.d
      - ./data/db:/var/lib/mysql
    environment:
      MYSQL_ROOT_HOST: "%"
      MYSQL_HOST: "localhost"
      MYSQL_ROOT_PASSWORD:  "123456"
      MYSQL_DATABASE: "Pomelo"
      MYSQL_USER: "pomelo"
      MYSQL_PASSWORD: "123456"
      MYSQL_LOG_CONSOLE: "true"
    restart: always
  
  lordofpomelo-app:
    build: .
    command: npm start
    links:
      - db
    ports:
      - 3001:3001
      - 3014:3014
      - 3010:3010
      - 3011:3011
    volumes:
      - .:/usr/src/app
      - /usr/src/app/web-server/node_modules
      - /usr/src/app/game-server/node_modules
      